---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/charadvachetan/learn
          searchPaths: spring-cloud-config/ConfigData
server:
  port: 8001
# For simplicity, disable security when posting to bus/refresh:  
management:
  security:
    enabled: false